### ISSUE TITLE
Overwrite names in addIntersect

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/PatientProfiles#143]
Currently we are not doing anything if new names are the same:
1. To check at the beginning of addDemographics and addIntersect the names that already exist and we have to change, you can modify the following function: https://github.com/oxford-pharmacoepi/PatientProfiles/blob/main/R/checks.R#L35-#L51 Change columns to original_name and new_name.
2. To build a function updateNames(x, namesToRepair). namesToRepair is a tibble with two columns (original_name and new_name) and if any of the columns of x has a name contained in original_name, the column name changes to new_name

**Comment by catalamarti** [comment]
Tests which is the current behavior if we have repeated column names

**Comment by MimiYuchenGuo** [comment]
For addIntersect, eg, if x contains column named count_All_0_to_Inf = c(1,1,1,1,1), then if even the true calcuated count_All_0_to_Inf by our function is c(4,3,3,2,2), the current function will output data with two columns of c(1,1,1,1,1), with different names: count_All_0_to_Inf, count_All_0_to_Inf:1

**Comment by catalamarti** [comment]
agreed that we overwrite @edward-burn @ilovemane @MimiYuchenGuo @Xintong-Li-ZnCu @catalamarti @nmercadeb

**Comment by MimiYuchenGuo** [comment]
@catalamarti overwrite in addDemo right?

**Comment by catalamarti** [comment]
AddDemo is already overwriting, the one that it is not currently doing it is addIntersect

**Comment by MimiYuchenGuo** [comment]
> AddDemo is already overwriting, the one that it is not currently doing it is addIntersect

ok i added test for that too
