### ISSUE TITLE
addIntersect when overlapTable is empty

### ISSUE THREAD

**Issue by KimLopezGuell** [oxford-pharmacoepi/PatientProfiles#175]
Doing the following:
cdm$cohort1 %>% addIntersect( "cohort2", filterVariable = "cohort_definition_id", filterId = 2 )
If cdm$cohort2 does not contain any rows with cohort_definition_id == 2, the function does not return any added column.
I imagine we would like it to return an added column c("NA", ..., "NA") as well.

**Comment by MimiYuchenGuo** [comment]
@catalamarti overwrite in addDemo right?
