### ISSUE TITLE
snake_case error

### ISSUE THREAD

**Issue by KimLopezGuell** [oxford-pharmacoepi/PatientProfiles#237]
Right now, if cohort names are not in snake_case, we throw an error an abort (for instance, in addCohortIntersect()). Should we only throw a warning and change the names to snake_case by default if possible? I.e. if a cohort is called "Diabetes@2" we could rename it "diabetes_2".
@catalamarti @edward-burn

**Comment by catalamarti** [comment]
Happy with that

**Comment by edward-burn** [comment]
Yep, would be nice to convert them I think
