### ISSUE TITLE
Maintain attributes after using "add" function ? 

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/PatientProfiles#242]
Currently when a function like `addDemographics` or `addCohortIntersect` that add columns is applied to a cohort the attributes are not maintained and they disappear. 
Keeping them may be of interest to later know what `cohort_definition_id = 1/2/3/4/...` means.
What do you think @edward-burn @KimLopezGuell

**Comment by edward-burn** [comment]
Yes please, this is an issue for cohort survival where adding cohort survival columns leads to losing the attributes.
https://github.com/darwin-eu-dev/CohortSurvival/blob/abd5d06b8fba130d43db39ed2d54e73c40ff78fb/tests/testthat/test-addCohortSurvival.R#L542

The functionality to store and then add back/ update attributes could live in patient profiles, but I think would ideally be in CDMConnector https://github.com/darwin-eu-dev/CDMConnector/issues/60

**Comment by catalamarti** [comment]
#244
