### ISSUE TITLE
Hex sticker design

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/PatientProfiles#66]

**Comment by catalamarti** [comment]
@Braventos The winner HexSticker is:
![Hex](https://user-images.githubusercontent.com/18575244/234545191-bd291635-0de0-40ca-887a-967e7153d7b0.png)
Could we have it but changing the font by the one here? :)
![image](https://user-images.githubusercontent.com/18575244/234545428-19a8b2a4-070f-40e4-bb7b-ce9556172b54.png)
Thank youuuuuu!

**Comment by Braventos** [comment]
Sure, here it is!
![patient profiles art final](https://user-images.githubusercontent.com/80947940/235120511-3941f7d2-1196-4e94-99ef-6f3445c49910.png)

I'll send you the final files by email
