### ISSUE TITLE
think about a general summariseCharacteristics() function

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/PatientProfiles#67]

**Comment by edward-burn** [comment]
One benefit of getting age and sex together is that we would not need to repeat joins to the person table (and would reduce the number of intermediate tables being created). Also if age and age groups were in the same function we wouldn't need to worry about how age was named etc *as it would be done together in the same function.

**Comment by edward-burn** [comment]
Currently done in TableOne package. As discussed, it would be nice to move the functionality into this package (in a future release)
