### ISSUE TITLE
Adding additional tests

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/PatientProfiles#75]

**Comment by edward-burn** [comment]
First @Xintong-Li-ZnCu, let's check test coverage to see if there are any gaps and where they are using `devtools::test_coverage()`

**Comment by Xintong-Li-ZnCu** [comment]
The overall coverage is 92.54% and almost all missed parts are `errorMessage$push` and `CDMConnector::computeQuery`
