### ISSUE TITLE
Built a function to check windows are valid

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/PatientProfiles#95]
Build a function called: checkWindow(window), that tests:
- If it is a vector convert into a list
- It must be a list of numeric vectors
- They can be length one or two
- No NA are allowed (NA changed to Inf)
- If length is one change to a vector with first and second element the same
- First element must be smaller or equal to the second one

return(window)

**Throw explanatory errors if window is not properly formatted**

Apply in all the functions instead of the tests that are applied now

**Comment by MimiYuchenGuo** [comment]
@catalamarti If changed "window" vector to list, the length check is a bit different. All the windows allowed in this package are all length(window)==1, whereas lengths(window) can be 1 or 2, then if 1 change it to 2 same numbers. Is this what we want?

**Comment by MimiYuchenGuo** [comment]
do we want window for this package as list(c(1,2)) or list(1,2)? @catalamarti

**Comment by catalamarti** [comment]
list(c(1,2)) because it can be then: list(c(1,2), c(2, 10)).
We allow multiple windows

**Comment by MimiYuchenGuo** [comment]
> list(c(1,2)) because it can be then: list(c(1,2), c(2, 10)). We allow multiple windows

I think currently all windows in this package's function is used as c(x,x), and none of them allows more than one window. Which ones are we going to allow more than one window? @catalamarti

**Comment by catalamarti** [comment]
For the moment in AddCohortIntersect but as @KimLopezGuell is working on it just write a function that she can do:
window <- checkWindow(window)

**Comment by MimiYuchenGuo** [comment]
> For the moment in AddCohortIntersect but as @KimLopezGuell is working on it just write a function that she can do: window <- checkWindow(window)

@catalamarti I have made a pull request with this function, if you could kindly review this is what you want. Currently, 365, list(365), c(365, 365), c(365,365, 365,....), list(365, 365, 365,...)... as long as only one unique value provided, it will all be convert to list(c(365, 365)). 

If given list(1,2,3), it will be converted to list(c(1,1),c(2,2),c(3,3)), but if given list(c(1,2,3)), if will throw error: "window can only contain two values: windowStart and windowEnd"
